```mermaid
graph TD
    Root --> .vscode
    Root --> assets
    Root --> messages
    Root --> project.inlang
    Root --> public
    Root --> src
```
```mermaid
graph TD
    Root --> .vscode
    Root --> assets
    Root --> messages
    Root --> project.inlang
    Root --> public
    Root --> src
```
```mermaid
graph TD
    Root --> .vscode
    Root --> assets
    Root --> messages
    Root --> project.inlang
    Root --> public
    Root --> src
```
```mermaid
graph TD
    Root --> .vscode
    Root --> assets
    Root --> messages
    Root --> project.inlang
    Root --> public
    Root --> src
```
